[Web]
    run_mode = "release"
    http_port = 14000
    service_name = "logservicev2"
    language = "zh_CN"
    read_timeOut = 120
    write_timeOut = 120
    connect_check_timeout = 10
    repository_request_timeout = 5

[Log]
    log_file_path = "./logservicev2.log"
    log_level = "debug"
    develop_mode = true
    max_age = 100
    max_backups = 20
    max_size = 100

[Redis]
    db = 2
    addr = "127.0.0.1:6379"
    password =  ""
    max_retries = 1
    min_idle_conns = 1

[Mysql]
    database = "paas_logservicev2_dev"
    host = "10.0.0.73"
    port = 3306
    username = "root"
    password = "Cocos@2021"

[Elasticsearch]
    address = ["http://10.0.3.116:9200"]
    username = "elastic"
    password = "123456"

[Tunnel]
    timeout = 20
    idle_conn_timeout = 60
    disable_keep_alives = true
    insecure_skip_verify = true

[Kafka]
    broker = ["10.0.3.116:9093"]