pipelines:
- name: demo
  sources:
  - name: mylog
    type: file
    addonMeta: true
    paths:
    - /home/logservice2/log/GameOperate.log
    fieldsUnderRoot: true
    fields:
      index: operator-55-1-3
      ip: 10.0.140.23
  sink:
    type: kafka
    balance: roundRobin
    brokers:
    - 10.0.3.116:9093
    compression: gzip
    topic: test
    codec: {}
