pipelines:
- name: demo
  sources:
  - name: operator
    type: file
    addonMeta: true
    paths:
    - /home/logservice2/log/GameOperate.log
    fieldsUnderRoot: true
    fields:
      index: operator-0-1-0
      ip: 10.0.133.53
  - name: DbManager
    type: file
    addonMeta: true
    paths:
    - /var/log/engine/DbManager.log
    fieldsUnderRoot: true
    fields:
      index: operator-0-1-0
      ip: 10.0.133.53
  - name: GameManager
    type: file
    addonMeta: true
    paths:
    - /var/log/engine/GameManager.log
    fieldsUnderRoot: true
    fields:
      index: operator-0-1-0
      ip: 10.0.133.53
  - name: GameServer
    type: file
    addonMeta: true
    paths:
    - /var/log/engine/GameServer.log
    fieldsUnderRoot: true
    fields:
      index: operator-0-1-0
      ip: 10.0.133.53
  - name: GateServer
    type: file
    addonMeta: true
    paths:
    - /var/log/engine/GateServer.log
    fieldsUnderRoot: true
    fields:
      index: operator-0-1-0
      ip: 10.0.133.53
  sink:
    type: kafka
    balance: roundRobin
    brokers:
    - 10.0.3.116:9093
    compression: gzip
    topic: logservice
    codec: {}
