pipelines:
- name: demo
  sources:
  - name: mylog
    type: file
    addonMeta: true
    paths:
    - /home/logservice2//log/GameOperate.log
    fieldsUnderRoot: true
    fields:
      index: x
      ip: x
  sink:
    type: kafka
    balance: roundRobin
    brokers:
    - 10.0.3.116:9092
    - ssss
    compression: gzip
    topic: test
    codec: {}
